### ISSUE TITLE
Wrong (inherited from Introclass) specification of digits in README

### ISSUE THREAD

**Issue by agodio** [Spirals-Team/IntroClassJava#5]
It says 

> digits -- compute the number of digits in an integer

but digits actually computes the reversed string

3.in:

> 690

3.out

> Enter an integer > 
> 0
> 9
> 6
> That's all, have a nice day!

**Comment by monperrus** [comment]
@tdurieux do you confirm?

**Comment by tdurieux** [comment]
I confirm it
