### ISSUE TITLE
Is there a diff view?

### ISSUE THREAD

**Issue by Kaka727** [Spirals-Team/IntroClassJava#6]
Hi, I'd like to know where can I find a diff view of the buggy programs and the patches.
In the /data folder of this repo, I only find the original buggy programs.

**Comment by tdurieux** [comment]
Hi,

Unfortunately, there is no diff since the benchmark does not contain a human patch.
There are only perfect versions of each program but the diff will be meaningful since there are not written by the same person (student vs. teacher).

**Comment by Kaka727** [comment]
That's ok. So where is the perfect version then?

**Comment by tdurieux** [comment]
Each project has a folder `ref/reference` that contains the perfect version, such as: https://github.com/Spirals-Team/IntroClassJava/tree/master/dataset/checksum/ref/reference

**Comment by Kaka727** [comment]
Thanks a lot!
