### ISSUE TITLE
Delete this issue... Was meant for the C version of this benchmark

### ISSUE THREAD

**Issue by agodio** [Spirals-Team/IntroClassJava#7]
Empty

**Comment by monperrus** [comment]
The error is not in the reference Java implementation?

**Comment by agodio** [comment]
Hi

No, since in this benchmark the tests compare the whole expected output. The python script (the one with the bug I'm reporting) doesn't event exist on this benchmark

Just for the curious, this is the issue on the C version.

https://github.com/ProgramRepair/IntroClass/issues/9

When I was about to open another issue (#10 in the C benchmark) I noticed I opened the wrong repo.

**Comment by monperrus** [comment]
ack thanks.
